services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./:/workspace:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  dev:
    image: node:22-alpine
    working_dir: /workspace
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/workspace
    command: ["sleep", "infinity"]
