services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      # share the whole project so Nginx can serve public and alias src
      - ./:/var/www:ro
      # your nginx vhost
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    image: php:8.3-fpm-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
    # optional: install extensions later with a custom Dockerfile if you need them

  composer:
    image: composer:2
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ["composer","--ansi"]

  dev:
    image: node:22-alpine
    working_dir: /workspace
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/workspace
    command: ["sleep", "infinity"]


# Examples
# docker compose run --rm composer init
# docker compose run --rm composer require some/vendor
